Added option to set USE_MODPACK_START_SCRIPT=false for CF modpacks (#591)

diff --git a/start-utils b/start-utils
--- a/start-utils
+++ b/start-utils
@@ -108,4 +108,8 @@ requireVar() {
     log "ERROR: $1 is required to be set"
     exit 1
   fi
+  if [ -z "${!1}" ]; then
+    log "ERROR: $1 is required to be set"
+    exit 1
+  fi
 }
