Fixed handling of query parameters in MODS url For #684

diff --git a/start-finalSetupModpack b/start-finalSetupModpack
--- a/start-finalSetupModpack
+++ b/start-finalSetupModpack
@@ -25,7 +25,7 @@ if [[ "$MODPACK" ]]; then
     if [[ "${MODPACK}" == *.zip ]]; then
       downloadUrl="${MODPACK}"
     else
-      downloadUrl=$(curl -Ls -o /dev/null -w %{url_effective} $MODPACK)
+      downloadUrl=$(curl -Ls -o /dev/null -w %{effective_url} $MODPACK)
       if ! [[ $downloadUrl == *.zip ]]; then
         log "ERROR Invalid URL given for MODPACK: $downloadUrl resolved from $MODPACK"
         log "      Must be HTTP or HTTPS and a ZIP file"
@@ -61,39 +61,31 @@ fi
 
 # If supplied with a URL for a plugin download it.
 if [[ "$MODS" ]]; then
+  if [ "$TYPE" = "SPIGOT" ]; then
+    out_dir=/data/plugins
+  else
+    out_dir=/data/mods
+  fi
+  mkdir -p "$out_dir"
+
   for i in ${MODS//,/ }
   do
     if isURL $i; then
-      if [[ $i == *.jar ]]; then
-        EFFECTIVE_MOD_URL=$i
-      else
-        EFFECTIVE_MOD_URL=$(curl -Ls -o /dev/null -w %{url_effective} $i)
-        if ! [[ $EFFECTIVE_MOD_URL == *.jar ]]; then
-          log "ERROR Invalid URL given in MODS: $EFFECTIVE_MOD_URL resolved from $i"
-          log "      Must be HTTP or HTTPS and a JAR file"
-          exit 1
+      log "Downloading mod/plugin $i ..."
+      effective_url=$(resolveEffectiveUrl "$i")
+      if isValidFileURL jar "${effective_url}"; then
+        out_file=$(getFilenameFromUrl "${effective_url}")
+        if ! curl -fsSL -o "${out_dir}/$out_file" "${effective_url}"; then
+          log "ERROR: failed to download from $i into $out_dir"
+          exit 2
         fi
-      fi
-
-      log "Downloading mod/plugin via HTTP"
-      log "  from $EFFECTIVE_MOD_URL ..."
-      if ! curl -sSL -o /tmp/${EFFECTIVE_MOD_URL##*/} $EFFECTIVE_MOD_URL; then
-        log "ERROR: failed to download from $EFFECTIVE_MOD_URL to /tmp/${EFFECTIVE_MOD_URL##*/}"
+      else
+        log "ERROR: $effective_url resolved from $i is not a valid jar URL"
         exit 2
       fi
-
-      if [ "$TYPE" = "SPIGOT" ]; then
-        mkdir -p /data/plugins
-        mv /tmp/${EFFECTIVE_MOD_URL##*/} /data/plugins/${EFFECTIVE_MOD_URL##*/}
-      else
-        mkdir -p /data/mods
-        mv /tmp/${EFFECTIVE_MOD_URL##*/} /data/mods/${EFFECTIVE_MOD_URL##*/}
-      fi
-      rm -f /tmp/${EFFECTIVE_MOD_URL##*/}
-
     else
       log "ERROR Invalid URL given in MODS: $i"
-      exit 1
+      exit 2
     fi
   done
 fi
@@ -103,7 +95,7 @@ if [[ "$MANIFEST" ]]; then
         EFFECTIVE_MANIFEST_FILE=$MANIFEST
     elif isURL "$MANIFEST"; then
         EFFECTIVE_MANIFEST_FILE=/tmp/manifest.json
-        EFFECTIVE_MANIFEST_URL=$(curl -Ls -o /dev/null -w %{url_effective} $MANIFEST)
+        EFFECTIVE_MANIFEST_URL=$(curl -Ls -o /dev/null -w %{effective_url} $MANIFEST)
         curl -Ls -o $EFFECTIVE_MANIFEST_FILE "$EFFECTIVE_MANIFEST_URL"
     else
         log "MANIFEST='$MANIFEST' is not a valid manifest url or location"
@@ -124,7 +116,7 @@ case "X$EFFECTIVE_MANIFEST_FILE" in
       do
         if [ ! -f $MOD_DIR/${p}_${f}.jar ]
         then
-          redirect_url="$(curl -Ls -o /dev/null -w %{url_effective} ${CURSE_URL_BASE}/${p})"
+          redirect_url="$(curl -Ls -o /dev/null -w %{effective_url} ${CURSE_URL_BASE}/${p})"
           url="$redirect_url/download/${f}/file"
           log Downloading curseforge mod $url
           #  Manifest usually doesn't have mod names. Using id should be fine, tho
