Update start-spiget
fix downloading (new) versionfile to actual versionfileNew location instead overwriting existing one, also add this task to full new download (first start, if no version file exists, it should also download one, or there would never be one)

diff --git a/start-spiget b/start-spiget
--- a/start-spiget
+++ b/start-spiget
@@ -35,7 +35,7 @@ getResourceFromSpiget() {
   if [ -f "$versionfile" ]; then
     if [[ -n $(find "$versionfile" -mmin +${SPIGET_DOWNLOAD_TOLERANCE}) ]]; then
       urlVersion="https://api.spiget.org/v2/resources/${resource}/versions/latest"
-      if ! curl -o "${versionfile}" -fsSL -H "User-Agent: itzg/minecraft-server" "${extraCurlArgs[@]}" "${urlVersion}"; then
+      if ! curl -o "${versionfileNew}" -fsSL -H "User-Agent: itzg/minecraft-server" "${extraCurlArgs[@]}" "${urlVersion}"; then
         log "ERROR failed to download resource version meta data '${resource}' from ${urlVersion}"
         exit 2
       fi
@@ -56,6 +56,11 @@ getResourceFromSpiget() {
     fi
   else
     if downloadResourceFromSpiget "${resource}"; then
+      urlVersion="https://api.spiget.org/v2/resources/${resource}/versions/latest"
+      if ! curl -o "${versionfileNew}" -fsSL -H "User-Agent: itzg/minecraft-server" "${extraCurlArgs[@]}" "${urlVersion}"; then
+        log "ERROR failed to download resource version meta data '${resource}' from ${urlVersion}"
+        exit 2
+      fi
       mv "${versionfileNew}" "${versionfile}"
     fi
   fi
