Pass JVM memory options to Spigot build Fixes #292

diff --git a/minecraft-server/start-deployBukkitSpigot b/minecraft-server/start-deployBukkitSpigot
--- a/minecraft-server/start-deployBukkitSpigot
+++ b/minecraft-server/start-deployBukkitSpigot
@@ -1,12 +1,21 @@
 #!/bin/bash
 
+set -e
+
 function buildSpigotFromSource {
   echo "Building Spigot $VANILLA_VERSION from source, might take a while, get some coffee"
   mkdir /data/temp
   cd /data/temp
+
+  jvmOpts="-Xms${INIT_MEMORY:-$MEMORY} -Xmx${MAX_MEMORY:-$MEMORY}"
+
   curl -sSL -o /data/temp/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar && \
-    java -jar /data/temp/BuildTools.jar --rev $VANILLA_VERSION 2>&1 |tee /data/spigot_build.log| while read l; do echo -n .; done; echo "done"
-  mv spigot-*.jar /data/spigot_server.jar
+    java $jvmOpts -jar /data/temp/BuildTools.jar --rev $VANILLA_VERSION 2>&1 |tee /data/spigot_build.log| while read l; do echo -n .; done; echo "done"
+  if ! mv spigot-*.jar /data/spigot_server.jar; then
+    echo "ERR failed to build Spigot"
+    cat /data/spigot_build.log
+    exit 1
+  fi
   mv craftbukkit-*.jar /data/craftbukkit_server.jar
   echo "Cleaning up"
   rm -rf /data/temp
