Changing to filter on Family, using custom in tests to bypass server download, updated readme

diff --git a/scripts/start-setupForgeApiMods b/scripts/start-setupForgeApiMods
--- a/scripts/start-setupForgeApiMods
+++ b/scripts/start-setupForgeApiMods
@@ -27,6 +27,9 @@ if isTrue "${REMOVE_OLD_FORGEAPI_MODS}" && [ -z "${MODS_FORGEAPI_KEY}" ]; then
   removeOldMods /data/mods
 fi
 
+# Family filter is on by default for Forge, Fabric, and Bukkit
+FILTER_BY_FAMILY=$( isFamily FORGE FABRIC BUKKIT )
+
 ensureModKey(){
   if [ -z "$MODS_FORGEAPI_KEY" ]; then
     log "ERROR: MODS_FORGEAPI_KEY REQUIRED to Connect to FORGE API, you supplied: ${MODS_FORGEAPI_KEY}"
@@ -105,14 +108,13 @@ modFileByProjectID(){
 
     # grabs the highest ID of the releaseTypes selected.
     # Default is 1 for Release, Beta is 2, and Alpha is 3. Using less than we can validate highest release.
-    # ORIGINAL_TYPE
     if [ $project_id_file_name ]; then
       # Looks for file by name
       current_project_file=$(jq -n "$project_files" | jq --arg FILE_NAME "$project_id_file_name" -jc '
         .data | map(select(.fileName<=($FILE_NAME))) | .[0] // empty')
-    elif ! isTrue "$MODS_FORGEAPI_IGNORE_GAMETYPE" && [[ ${ORIGINAL_TYPE,,} != "vanilla" ]]; then
+    elif $( ! isTrue "$MODS_FORGEAPI_IGNORE_GAMETYPE" ) && $FILTER_BY_FAMILY ; then
       # Looks for file by version and server type in lowercase
-      current_project_file=$(jq -n "$project_files" | jq --arg RELEASE_FILTER "$RELEASE_NUMBER_FILTER" --arg GAME_TYPE ${ORIGINAL_TYPE,,} -jc '
+      current_project_file=$(jq -n "$project_files" | jq --arg RELEASE_FILTER "$RELEASE_NUMBER_FILTER" --arg GAME_TYPE ${FAMILY,,} -jc '
         .data | sort_by(.id) | reverse | map(select(.gameVersions[] | ascii_downcase | contains ($GAME_TYPE))) | map(select(.releaseType<=($RELEASE_FILTER|tonumber))) | .[0] // empty')
     else
       # Looks for file by version only.
@@ -140,7 +142,7 @@ modFileByProjectID(){
     index=$(($index + $pageSize))
   done
   if [ ! "$PROJECT_FILE" ]; then
-    log "ERROR: Unable to retrieve any files for ${project_id}, Release Type: ${RELEASE_NUMBER_FILTER}, GAME_TYPE: ${ORIGINAL_TYPE,,}"
+    log "ERROR: Unable to retrieve any files for ${project_id}, Release Type: ${RELEASE_NUMBER_FILTER}, FAMILY_TYPE: ${FAMILY,,}"
     exit 2
   fi
 }
@@ -158,7 +160,7 @@ downloadModPackfromModFile() {
   # trys to make the output directory incase it doesnt exist.
   mkdir -p "$out_dir"
   echo "Downloading ${download_url}"
-  if ! get -o "${out_dir}/${file_name}" $download_url ; then 
+  if ! get --skip-up-to-date -o "${out_dir}/${file_name}" $download_url ; then
     log "ERROR: failed to download from ${download_url}"
     exit 2
   fi
