Added github actions debug support
Also
- added use of fileNotExists

diff --git a/scripts/start-setupModpack b/scripts/start-setupModpack
--- a/scripts/start-setupModpack
+++ b/scripts/start-setupModpack
@@ -23,38 +23,22 @@ if isTrue "${REMOVE_OLD_MODS}" && [ -z "${MODS_FILE}" ]; then
 fi
 
 function handlePackwiz() {
-# If packwiz url passed, bootstrap packwiz and update mods before other modpack processing
-if [[ "${PACKWIZ_URL:-}" ]]; then
-  # Ensure we have the latest packwiz bootstrap installer
-  latestPackwiz=$(get_from_gh "https://api.github.com/repos/packwiz/packwiz-installer-bootstrap/releases/latest")
-  if [[ -z "${latestPackwiz}" ]]; then
-    log "WARNING: Could not retrieve Packwiz bootstrap installer release information"
-  else
-    isDebugging && log "Latest packwiz ${latestPackwiz}"
-    latestPackwizVer=$(echo "${latestPackwiz}" | jq --raw-output '.tag_name')
-    latestPackwizUrl=$(echo "${latestPackwiz}" | jq --raw-output '.assets[] | select(.name | match("packwiz-installer-bootstrap.jar")) | .url')
-   : "${PACKWIZ_BOOTSTRAP_JAR:=packwiz-installer-bootstrap_${latestPackwizVer}.jar}"
-   if [[ ! -e $PACKWIZ_BOOTSTRAP_JAR ]]; then
-      log "Downloading Packwiz ${latestPackwizVer}"
-      if ! curl -H "Accept:application/octet-stream" -o "$PACKWIZ_BOOTSTRAP_JAR" -fsSL ${latestPackwizUrl}; then
-        log "ERROR: failed to download Packwiz bootstrap installer"
-        exit 1
-      fi
+  # If packwiz url passed, bootstrap packwiz and update mods before other modpack processing
+  if [[ "${PACKWIZ_URL:-}" ]]; then
+    if ! packwizInstaller=$(mc-image-helper maven-download \
+                           --maven-repo=https://maven.packwiz.infra.link/repository/release/ \
+                           --group=link.infra.packwiz --artifact=packwiz-installer --classifier=dist \
+                           --skip-existing); then
+      log "ERROR: failed to get packwiz installer"
+      exit 1
+    fi
+
+    log "Running packwiz installer against URL: ${PACKWIZ_URL}"
+    if ! java -cp "${packwizInstaller}" link.infra.packwiz.installer.Main "${PACKWIZ_URL}"; then
+      log "ERROR failed to run packwiz installer"
+      exit 1
     fi
   fi
-  log "Running packwiz installer against URL: ${PACKWIZ_URL}"
-  java -jar "${PACKWIZ_BOOTSTRAP_JAR}" -g -s server "${PACKWIZ_URL}"
-  #if bootstrap download fails, download installer manually - then run without updating
-  returnVal=$?
-  if [[ $returnVal ]]; then
-    latestPackwizInstaller=$(get_from_gh "https://api.github.com/repos/packwiz/packwiz-installer/releases/latest")
-    latestPackwizInstallerVer=$(echo "${latestPackwizInstaller}" | jq --raw-output '.tag_name')
-    latestPackwizInstallerUrl=$(echo "${latestPackwizInstaller}" | jq --raw-output '.assets[] | select(.name | match("packwiz-installer.jar")) | .url')
-    log "Packwiz couldn't update - Downloading Packwiz Installer ${latestPackwizInstallerVer}"
-    get_from_gh "${latestPackwizInstallerUrl}" -H "Accept:application/octet-stream" -o "packwiz-installer.jar"
-    java -jar "${PACKWIZ_BOOTSTRAP_JAR}" -g -bootstrap-no-update -s server "${PACKWIZ_URL}"
-  fi
-fi
 }
 
 function handleModpackListOrFile() {
