removing logging that was used for testing, deduped download code

diff --git a/scripts/start-setupVanillaTweaks b/scripts/start-setupVanillaTweaks
--- a/scripts/start-setupVanillaTweaks
+++ b/scripts/start-setupVanillaTweaks
@@ -27,6 +27,24 @@ if isTrue "${REMOVE_OLD_VANILLATWEAKS}"; then
   fi
 fi
 
+# Gets the download url and downloads the actual files.
+getUrlAndDownload(){
+  URL_SUFFIX=$1
+  OUTPUT_FILE=$2
+  BASE_ZIPDATA_URL="https://vanillatweaks.net/assets/server/${URL_SUFFIX}.php"
+
+  DOWNLOAD_URL=$(curl -X POST -F "packs=${DATAPACKS}" -F "version=${VT_VERSION}" $VT_ZIPDATA_URL | jq -r '.link // empty')
+  if [ ! "$DOWNLOAD_URL" ]; then
+    log "ERROR: unable to retrieve ${URL_SUFFIX} packs from vanillatweaks.net!"
+    exit 2
+  fi
+
+  if ! get -o $OUTPUT_FILE "https://vanillatweaks.net${DOWNLOAD_URL}"; then
+    log "ERROR: failed to download ${URL_SUFFIX} from ${DOWNLOAD_URL}"
+    exit 2
+  fi
+}
+
 # Download and unzip datapacks
 downloadDatapacks(){
   VT_FILE=$1
@@ -35,29 +53,17 @@ downloadDatapacks(){
     log "ERROR: unable to retrieve datapacks from ${VT_FILE}"
     exit 2
   fi
-  VT_ZIPDATA_URL="https://vanillatweaks.net/assets/server/zipdatapacks.php"
 
-  log "DATAPACKS: ${DATAPACKS}, VT_VERSION: ${VT_VERSION}"
-  log $(curl -X POST -F "packs=${DATAPACKS}" -F "version=${VT_VERSION}" $VT_ZIPDATA_URL)
-  DOWNLOAD_URL=$(curl -X POST -F "packs=${DATAPACKS}" -F "version=${VT_VERSION}" $VT_ZIPDATA_URL | jq -r '.link // empty')
-  log "DOWNLOAD_URL: ${DOWNLOAD_URL}"
-  if [ ! "$DOWNLOAD_URL" ]; then
-    log "ERROR: unable to retrieve datapack DOWNLOAD_URL from vanillatweaks.net!"
-    exit 2
-  fi
-
-  TEMPZIP=/tmp/vanillatweaks.zip
-  if ! get -o $TEMPZIP "https://vanillatweaks.net${DOWNLOAD_URL}"; then
-    log "ERROR: failed to download datapacks from ${DOWNLOAD_URL}"
-    exit 2
-  fi
+  URL_SUFFIX="zipdatapacks"
+  OUTPUT_FILE="/tmp/vanillatweaks.zip"
+  getUrlAndDownload $URL_SUFFIX $OUTPUT_FILE
 
   mkdir -p "$DATAPACKS_DIR"
-  if ! unzip -o -d "$DATAPACKS_DIR" $TEMPZIP; then
-    log "ERROR: failed to unzip the datapacks ${DATAPACKS} from ${TEMPZIP}"
+  if ! unzip -o -d "$DATAPACKS_DIR" $OUTPUT_FILE; then
+    log "ERROR: failed to unzip the datapacks ${DATAPACKS} from ${OUTPUT_FILE}"
   fi
 
-  rm -f $TEMPZIP
+  rm -f $OUTPUT_FILE
 }
 
 # Download and move crafting tweaks
@@ -68,19 +74,9 @@ downloadCraftingtweaks(){
     log "ERROR: unable to retrieve crafting tweaks from ${VT_FILE}"
     exit 2
   fi
-  VT_ZIPDATA_URL="https://vanillatweaks.net/assets/server/zipcraftingtweaks.php"
-  
-  DOWNLOAD_URL=$(curl -X POST -F "packs=${CRAFTINGTWEAKS}" -F "version=${VT_VERSION}" $VT_ZIPDATA_URL | jq -r '.link // empty')
-  if [ ! "$DOWNLOAD_URL" ]; then
-    log "ERROR: unable to retrieve crafting tweak DOWNLOAD_URL from vanillatweaks.net!"
-    exit 2
-  fi
 
   mkdir -p "$DATAPACKS_DIR"
-  if ! get -o $DATAPACKS_DIR/crafting_tweaks.zip "https://vanillatweaks.net${DOWNLOAD_URL}"; then
-    log "ERROR: failed to download crafting tweaks from ${DOWNLOAD_URL}"
-    exit 2
-  fi
+  getUrlAndDownload "zipcraftingtweaks" "${DATAPACKS_DIR}/crafting_tweaks.zip"
 }
 
 # Download resource packs
@@ -91,19 +87,9 @@ downloadResourcepacks(){
     log "ERROR: unable to retrieve resourcepacks from ${VT_FILE}"
     exit 2
   fi
-  VT_ZIPDATA_URL="https://vanillatweaks.net/assets/server/zipresourcepacks.php"
-
-  DOWNLOAD_URL=$(curl -X POST -F "packs=${RESOURCEPACKS}" -F "version=${VT_VERSION}" $VT_ZIPDATA_URL | jq -r '.link // empty')
-  if [ ! "$DOWNLOAD_URL" ]; then
-    log "ERROR: unable to retrieve resourcepacks DOWNLOAD_URL from vanillatweaks.net!"
-    exit 2
-  fi
 
   mkdir -p "$RESOURCEPACKS_DIR"
-  if ! get -o $RESOURCEPACKS_DIR/resourcepacks.zip "https://vanillatweaks.net${DOWNLOAD_URL}"; then
-    log "ERROR: failed to download resourcepacks from ${DOWNLOAD_URL}"
-    exit 2
-  fi
+  getUrlAndDownload "zipresourcepacks" "${RESOURCEPACKS_DIR}/resourcepacks.zip"
 }
 
 # Example: VANILLATWEAKS_SHARECODE=MGr52E
@@ -119,7 +105,6 @@ if [[ "$VANILLATWEAKS_SHARECODE" ]]; then
     fi
     VANILLATWEAKS_FILE+="${TMP_FILE},"
   done
-  log "VANILLATWEAKS_FILE: ${VANILLATWEAKS_FILE}"
 fi
 
 # Use vanillatweaks file to specify VT and datapacks and crafting tweaks
@@ -150,10 +135,6 @@ if [[ "$VANILLATWEAKS_FILE" ]]; then
       rm -f $VT_FILE
     fi
   done
-  FILES=$(ls -l $RESOURCEPACKS_DIR)
-  log $FILES
-  FILES=$(ls -l $DATAPACKS_DIR)
-  log $FILES
 fi
 
 exec "${SCRIPTS:-/}start-setupDatapack" "$@"
