restructure updateGTNH, add updateGTNHRessource

diff --git a/scripts/start-deployGTNH b/scripts/start-deployGTNH
--- a/scripts/start-deployGTNH
+++ b/scripts/start-deployGTNH
@@ -70,79 +70,94 @@ function deleteGTNHbackup(){
   fi
 }
 
+function updateGTNHRessource(){
+  local resource="$1"
+  local new_resource="$2"
+  log "Trying to update $resource"
+
+  if [[ -z "$resource" ]]; then
+    logWarning "No resource specified for update"
+    return 0
+  fi
+
+  if [[ -d "$resource" ]]; then
+    log "Deleting folder: $resource"
+    if ! rm -rf "$resource"; then
+      logError "Failed to delete folder: $resource"
+      exit 1
+    fi
+    if [[ -d "$new_resource" ]]; then
+      log "Copying $new_resource to /data"
+      if ! cp -r "$new_resource" "/data/"; then
+        logError "Failed to copy $new_resource to /data"
+        exit 1
+      fi
+    else
+      logWarning "Folder $new_resource not found in the unzipped data!"
+    fi
+    return 0
+  elif [[ -f "$resource" ]]; then
+    log "Deleting file: $resource"
+    if ! rm -f "$resource"; then
+      logError "Failed to delete file: $resource"
+      exit 1
+    fi
+    if [[ -f "$new_resource" ]]; then
+      log "Copying $new_resource to /data"
+      if ! cp "$new_resource" "/data/"; then
+        logError "Failed to copy $new_resource to /data"
+        exit 1
+      fi
+    else
+      logWarning "File $new_resource not found in the unzipped data!"
+    fi
+    return 0
+  fi
+
+  logWarning "Resource $resource does not exist"
+  return 0
+}
+
 function updateGTNH(){
   # Get the current date and time
-  current_datetime=$(date +%Y-%m-%dT%H:%M)
+  local current_datetime=$(date +%Y-%m-%dT%H:%M)
   
   # Define folders and files to update
-  folders_to_update=("libraries" "mods" "resources" "scripts")
-  files_to_update=("lwjgl3ify-forgePatches.jar" "java9args.txt" "startserver-java9.bat" "startserver-java9.sh" "forge-1.7.10-10.13.4.1614-1.7.10-universal.jar" "startserver.bat" "startserver.sh" "server-icon.png")
-  config_folder="config"
-  backup_folder="/data/gtnh-upgrade-$current_datetime"
-  journey_map_folder="JourneyMapServer"
-
-  # Delete specified folders if they exist
-  for folder in "${folders_to_update[@]}"; do
-      folder_path="/data/$folder"
-      if [[ -d "$folder_path" ]]; then
-          log "Deleting folder: $folder_path"
-          rm -rf "$folder_path"
-      fi
-  done
-
-  # Delete specific files if they exist
-  for file in "${files_to_update[@]}"; do
-      file_path="/data/$file"
-      if [[ -f "$file_path" ]]; then
-          log "Deleting file: $file_path"
-          rm -f "$file_path"
-      fi
-  done
+  # base_dir is already defined in handleGTNH function
+  local folders_to_update=("libraries" "mods" "resources" "scripts")
+  local files_to_update=("lwjgl3ify-forgePatches.jar" "java9args.txt" "startserver-java9.bat" "startserver-java9.sh" "forge-1.7.10-10.13.4.1614-1.7.10-universal.jar" "startserver.bat" "startserver.sh" "server-icon.png")
+  local config_folder="config"
+  local backup_folder="/data/gtnh-upgrade-$current_datetime"
+  local journey_map_folder="JourneyMapServer"
 
   # Backup the config folder
   if [[ -d "/data/$config_folder" ]]; then
       log "Creating backup of /data/$config_folder at $backup_folder"
       cp -r "/data/$config_folder" "$backup_folder"
-      log "Deleting original /data/$config_folder"
-      rm -rf "/data/$config_folder"
   fi
 
-  # Updating the required folders in data directory
-  for folder in "${folders_to_update[@]}" "$config_folder"; do
-    if [[ -d "$base_dir/$folder" ]]; then
-      log "Copying $folder to /data"
-      cp -r "$base_dir/$folder" "/data/"
-    else
-      logWarning "Folder $folder not found in the unzipped data!"
-    fi
-  done
-        
-  # Copy specific files to the /data directory
-  for file in "${files_to_update[@]}"; do
-    if [[ -f "$base_dir/$file" ]]; then
-      log "Copying $file to /data"
-      cp "$base_dir/$file" "/data/"
-    else
-      logWarning "File $file not found in the unzipped data!"
-    fi
-  done
+# Update ressources from unpacked server files to /data
+  for ressource in "${folders_to_update[@]}" "$config_folder ${files_to_update[@]}"; do
+    local resource_path="/data/$ressource"
+    local new_resource_path="$base_dir/$ressource"
 
-  # Ensure the config folder exists
-  if [[ ! -d "$config_folder" ]]; then
-      log "$config_folder does not exist. Creating it now."
-      mkdir -p "$config_folder"
-  fi
+    updateGTNHRessource "$resource_path" "$new_resource_path"
+  done
 
   # Restore JourneyMapServer folder from backup
   if [[ -d "$backup_folder/$journey_map_folder" ]]; then
-      log "Restoring $journey_map_folder to $config_folder"
-      cp -r "$backup_folder/$journey_map_folder" "$config_folder/"
+    if [[ ! -d "/data/$config_folder" ]]; then
+      log "/data/$config_folder folder does not exist. Creating it now."
+      mkdir -p "/data/$config_folder"
+    fi
+      log "Restoring $journey_map_folder to /data/$config_folder"
+      cp -r "$backup_folder/$journey_map_folder" "/data/$config_folder/"
   else
       logWarning "$journey_map_folder not found in backup!"
   fi
 
   # Copy the changelog file to /data
-  gtnh_changelog_file=$(mc-image-helper find --max-depth=1 --type=file --name=changelog*.md "$base_dir")
+  local gtnh_changelog_file=$(mc-image-helper find --max-depth=1 --type=file --name=changelog*.md "$base_dir")
   if [[ -n "$gtnh_changelog_file" ]]; then
     log "Copying changelog file to /data"
     cp -f "$gtnh_changelog_file" /data/
