adding the install-neoforge arguments to allow installations from a file locally

diff --git a/scripts/start-deployNeoForge b/scripts/start-deployNeoForge
--- a/scripts/start-deployNeoForge
+++ b/scripts/start-deployNeoForge
@@ -9,7 +9,12 @@ isDebugging && set -x
 
 resultsFile=/data/.run-neoforge.env
 
-if ! mc-image-helper install-neoforge \
+if [[ ${NEOFORGE_INSTALLER} ]]; then
+  if ! mc-image-helper install-neoforge --neoforge-installer="${NEOFORGE_INSTALLER}" --output-directory=/data --results-file=${resultsFile} --minecraft-version="${VERSION}" --force-reinstall="${NEOFORGE_FORCE_REINSTALL}"; then
+      logError "Failed to installForge given installer ${NEOFORGE_INSTALLER}"
+      exit 1
+  fi
+elif ! mc-image-helper install-neoforge \
   --output-directory=/data \
   --results-file=${resultsFile} \
   --minecraft-version="${VERSION}" \
