range of fixes to deployGTNH and setupModpack

diff --git a/scripts/start-setupModpack b/scripts/start-setupModpack
--- a/scripts/start-setupModpack
+++ b/scripts/start-setupModpack
@@ -255,6 +255,12 @@ function handleGenericPacks() {
 }
 
 function handleGTNH() {
+  # Possible Options: VERSION_NUMBER, latest, latest-dev
+  : "${GTNH_PACK_VERSION:=latest}"
+  : "${GTNH_DELETE_BACKUPS:=false}"
+  : "${SKIP_GTNH_UPDATE_CHECK:=false}"
+  log "GTNH VAR CHECK $GTNH_DELETE_BACKUPS, $GTNH_PACK_VERSION, $TYPE, $SKIP_GTNH_UPDATE_CHECK"
+
   if isTrue "$GTNH_DELETE_BACKUPS"; then
     log "Start deleting all config backups"
     if deleted_backups="$(mc-image-helper find --name="gtnh-upgrade-*" --delete --max-depth=1 --type directory /data)" ; then
@@ -264,8 +270,9 @@ function handleGTNH() {
     fi
   fi
 
-  if [[ -z $GTNH_PACK_VERSION ]] && isFalse "${SKIP_GTNH_UPDATE_CHECK:-false}" ; then
+  if [[ -n $GTNH_PACK_VERSION ]] && isFalse "$SKIP_GTNH_UPDATE_CHECK" ; then
     gtnh_download_path=""
+    current_java_version=$(mc-image-helper java-release)
     
     if ! mapfile -t packs < <(curl -sfL 'http://downloads.gtnewhorizons.com/ServerPacks/?raw'); then
       logError "Failed to retrieve data from http://downloads.gtnewhorizons.com/ServerPacks/?raw"
@@ -275,8 +282,9 @@ function handleGTNH() {
     log "Start locating server files..."
     for pack in "${packs[@]}"; do
       # Extract the Java version(s) from the pack filename
-      pack_java_version=$(basename "$pack" | grep -Eo 'Java_[0-9]+(-[0-9]+)?' | sed 's/Java_//')
-      current_java_version=$(mc-image-helper java-release)
+      if ! pack_java_version=$(basename "$pack" | grep -Eo 'Java_[0-9]+(-[0-9]+)?' | sed 's/Java_//'); then
+      logWarning "Could not parse java version of $pack"
+      fi
 
       # Skip the pack if the current Java version is not compatible
       if [[ "$pack_java_version" == *-* ]]; then
@@ -296,14 +304,23 @@ function handleGTNH() {
       fi
 
       # Extract version numbers and release type (beta or RC) from the file names
-      pack_version=$(basename "$pack" | grep -Eo '[0-9]+(\.[0-9]+)+')
-      pack_release_type=$(basename "$pack" | grep -Eo '(beta|RC)(-[0-9]+)?' || echo "")
-      current_version=$(basename "$gtnh_download_path" | grep -Eo '[0-9]+(\.[0-9]+)+')
-      current_release_type=$(basename "$gtnh_download_path" | grep -Eo '(beta|RC)(-[0-9]+)?' || echo "")
+      
+      if ! pack_version=$(basename "$pack" | grep -Eo '[0-9]+(\.[0-9]+)+'); then
+      logWarning "Could not parse version of $pack"
+      fi
+      if ! pack_release_type=$(basename "$pack" | grep -Eo '(beta|RC)(-[0-9]+)?' || echo ""); then
+      logWarning "Could not parse release type of $pack"
+      fi
+      if ! current_version=$(basename "$gtnh_download_path" | grep -Eo '[0-9]+(\.[0-9]+)+'); then
+      log "Could not parse version of selected download path. String might be empty."
+      fi
+      if ! current_release_type=$(basename "$gtnh_download_path" | grep -Eo '(beta|RC)(-[0-9]+)?' || echo ""); then
+      log "Could not parse release type of selected download path. String might be empty."
+      fi
       # Check if the pack matches the desired type based on GTNH_PACK_VERSION:
       # - If GTNH_PACK_VERSION is "latest-dev", only consider beta packs (path contains "/betas/").
       # - If GTNH_PACK_VERSION is "latest", only consider non-beta packs (path does not contain "/betas/").
-      if ([[ $pack == */betas/* ]] && [[ $GTNH_PACK_VERSION == "latest-dev" ]]) || ([[ ! $pack == */betas/* ]] && [[ $GTNH_PACK_VERSION == "latest" ]]); then
+      if [[ ($pack == "*/betas/*" && $GTNH_PACK_VERSION == "latest-dev") || ($pack != "*/betas/*" && $GTNH_PACK_VERSION == "latest") ]]; then
         # Compare versions and update gtnh_download_path if pack is newer
         # Check if the current version is unset or if the pack version is newer than the current version.
         # This comparison uses version sorting to determine the latest version.
@@ -325,7 +342,7 @@ function handleGTNH() {
           fi
         fi
       else
-        if [ "$pack_version" = "$GTNH_PACK_VERSION" ] || [ "$pack_version-$pack_release_type" = "$GTNH_PACK_VERSION" ]; then
+        if [[ "$pack_version" == "$GTNH_PACK_VERSION" || "$pack_version-$pack_release_type" == "$GTNH_PACK_VERSION" ]]; then
           log "Found exact match $pack_version = $GTNH_PACK_VERSION! Select $pack_version for download."
           gtnh_download_path="$pack"
           break
@@ -374,7 +391,7 @@ function handleGTNH() {
       fi
 
       # Split installation from update path. Check for version file.
-      if [ -f /data/.gtnh-version ]; then
+      if [[ -f /data/.gtnh-version ]]; then
         log ".gtnh-version file detected! Assuming old version already exists. Proceed updating existing server..."
         # Get the current date and time
         current_datetime=$(date +%Y-%m-%dT%H:%M)
@@ -389,7 +406,7 @@ function handleGTNH() {
         # Delete specified folders if they exist
         for folder in "${folders_to_update[@]}"; do
             folder_path="/data/$folder"
-            if [ -d "$folder_path" ]; then
+            if [[ -d "$folder_path" ]]; then
                 log "Deleting folder: $folder_path"
                 rm -rf "$folder_path"
             fi
@@ -398,14 +415,14 @@ function handleGTNH() {
         # Delete specific files if they exist
         for file in "${files_to_update[@]}"; do
             file_path="/data/$file"
-            if [ -f "$file_path" ]; then
+            if [[ -f "$file_path" ]]; then
                 log "Deleting file: $file_path"
                 rm -f "$file_path"
             fi
         done
 
         # Backup the config folder
-        if [ -d "/data/$config_folder" ]; then
+        if [[ -d "/data/$config_folder" ]]; then
             log "Creating backup of /data/$config_folder at $backup_folder"
             cp -r "/data/$config_folder" "$backup_folder"
             log "Deleting original /data/$config_folder"
@@ -414,7 +431,7 @@ function handleGTNH() {
 
         # Updating the required folders in data directory
         for folder in "${folders_to_update[@]}" "$config_folder"; do
-          if [ -d "$base_dir/$folder" ]; then
+          if [[ -d "$base_dir/$folder" ]]; then
             log "Copying $folder to /data"
             cp -r "$base_dir/$folder" "/data/"
           else
@@ -424,7 +441,7 @@ function handleGTNH() {
         
         # Copy specific files to the /data directory
         for file in "${files_to_update[@]}"; do
-          if [ -f "$base_dir/$file" ]; then
+          if [[ -f "$base_dir/$file" ]]; then
             log "Copying $file to /data"
             cp "$base_dir/$file" "/data/"
           else
@@ -433,13 +450,13 @@ function handleGTNH() {
         done
 
         # Ensure the config folder exists
-        if [ ! -d "$config_folder" ]; then
+        if [[ ! -d "$config_folder" ]]; then
             log "$config_folder does not exist. Creating it now."
             mkdir -p "$config_folder"
         fi
 
         # Restore JourneyMapServer folder from backup
-        if [ -d "$backup_folder/$journey_map_folder" ]; then
+        if [[ -d "$backup_folder/$journey_map_folder" ]]; then
             log "Restoring $journey_map_folder to $config_folder"
             cp -r "$backup_folder/$journey_map_folder" "$config_folder/"
         else
@@ -458,7 +475,7 @@ function handleGTNH() {
         cp -R -f "${base_dir}"/* /data
       fi
       # Update .gtnh-version
-      echo "$(basename "$gtnh_download_path")" > /data/.gtnh-version
+      basename "$gtnh_download_path" > /data/.gtnh-version
       # Cleaning up
       rm -rf "$original_base_dir"
     
