Update Poseidon

diff --git a/scripts/start-deployPoseidon b/scripts/start-deployPoseidon
--- a/scripts/start-deployPoseidon
+++ b/scripts/start-deployPoseidon
@@ -7,7 +7,13 @@ set -e
 isDebugging && set -x
 
 resolveVersion
-: "${POSEIDON_RELEASE:=latest}"
+
+if [ "${VERSION}" != "b1.7.3" ]; then
+  logError "Poseidon server type only supports VERSION=b1.7.3"
+  exit 1
+fi
+
+# : "${POSEIDON_RELEASE:=latest}" placeholder until I figure out how to add version selection with mc-image-helper
 : "${POSEIDON_TYPE:=poseidon}"
 
 if [[ ${POSEIDON_TYPE^^} = UBERBUKKIT ]]; then
@@ -16,34 +22,13 @@ else
   poseidonRepo="retromcorg/Project-Poseidon"
 fi
 
-poseidonReleasesUrl="https://api.github.com/repos/${poseidonRepo}/releases"
-
-if [[ ${POSEIDON_RELEASE^^} = LATEST ]]; then
-  poseidonReleaseUrl=${poseidonReleasesUrl}/latest
-else
-  poseidonReleaseUrl=${poseidonReleasesUrl}/tags/${POSEIDON_RELEASE}
-fi
-
-latestAsset=$(
-  curl -fsSL ${poseidonReleaseUrl} | \
-    jq '.assets[] | select(.name | match(".project-poseidon-*"))'
-)
-
-if [[ -z "${latestAsset}" ]]; then
-  logError "Latest release of Poseidon is missing .jar asset"
-  exit 1
-fi
-
-isDebugging && log "Latest asset ${latestAsset}"
-latestJarName=$(echo ${latestAsset} | jq --raw-output '.name')
-latestJarId=$(echo ${latestAsset} | jq --raw-output '.id')
-
-
-export SERVER="/data/${latestJarName}"
-
-if [ ! -f ${SERVER} ]; then
-  log "Downloading ${latestJarName}"
-  curl -H "Accept:application/octet-stream" -o "$SERVER" -fsSL https://api.github.com/repos/retromcorg/Project-Poseidon/releases/assets/${latestJarId}
+if ! SERVER=$(mc-image-helper github download-latest-asset \
+  --output-directory=/data \
+  --name-pattern="^(?!original-).+\.jar" \
+  ${poseidonRepo}
+  ); then
+    logError "Failed to download ${POSEIDON_TYPE}"
+    exit 1
 fi
 
 export SERVER
