Use KettingLauncher (#2655)

diff --git a/scripts/start-deployKetting b/scripts/start-deployKetting
--- a/scripts/start-deployKetting
+++ b/scripts/start-deployKetting
@@ -4,26 +4,27 @@
 . "${SCRIPTS:-/}start-utils"
 isDebugging && set -x
 
-: "${FORGE_VERSION:=${FORGEVERSION:-RECOMMENDED}}"
-: "${KETTING_VERSION:=}"
-: "${KETTING_TAG:=${KETTING_VERSION:0:7}}"
+if ! SERVER=$(mc-image-helper github download-latest-asset \
+  --output-directory=/data \
+  --name-pattern="kettinglauncher-.+?(?<!-sources)\.jar" \
+  kettingpowered/kettinglauncher
+  ); then
+    log "ERROR: failed to download Ketting launcher"
+    exit 1
+fi
+
+export SERVER
 
 resolveVersion
 
-if ! downloadUrl="https://github.com/kettingpowered/Ketting-1-20-x/releases/download/${KETTING_TAG}/ketting-${VERSION}-${FORGE_VERSION}-${KETTING_VERSION}-server.jar"; then
-  log "ERROR failed to locate latest Ketting download for ${VERSION}. Is that version supported?"
-  exit 1
+EXTRA_ARGS+="-minecraftVersion $VERSION"
+if [[ ${KETTING_VERSION:-} ]]; then
+  EXTRA_ARGS+="-kettingVersion $KETTING_VERSION"
 fi
-
-if [[ $downloadUrl == null ]]; then
-  log "ERROR Ketting does not seem to be available for $VERSION"
-  exit 1
+if [[ ${FORGE_VERSION:-} ]]; then
+  EXTRA_ARGS+="-forgeVersion $FORGE_VERSION"
 fi
-
-if ! SERVER=$(get --output-filename --skip-up-to-date --output /data "$downloadUrl"); then
-  log "ERROR: failed to download Ketting server jar from $downloadUrl"
-  exit 1
-fi
+export EXTRA_ARGS
 
 export SERVER
 export FAMILY=HYBRID
