Restored error handling when missing vanilla version (#1389)

diff --git a/scripts/start-deployVanilla b/scripts/start-deployVanilla
--- a/scripts/start-deployVanilla
+++ b/scripts/start-deployVanilla
@@ -8,27 +8,25 @@ set -o pipefail
 export SERVER="minecraft_server.${VANILLA_VERSION// /_}.jar"
 
 if [ ! -e "$SERVER" ] || [ -n "$FORCE_REDOWNLOAD" ]; then
-  log "Downloading $SERVER ..."
+  log "Locating download for $SERVER ..."
   debug "Finding version manifest for $VANILLA_VERSION"
   versionManifestUrl=$(get 'https://launchermeta.mojang.com/mc/game/version_manifest.json' | jq --arg VANILLA_VERSION "$VANILLA_VERSION" --raw-output '[.versions[]|select(.id == $VANILLA_VERSION)][0].url')
   result=$?
   if [ $result != 0 ]; then
-    log "ERROR failed to obtain version manifest URL ($result)"
+    log "ERROR: failed to obtain version manifest URL ($result)"
     exit 1
   fi
   if [ "$versionManifestUrl" = "null" ]; then
-    log "ERROR couldn't find a matching manifest entry for $VANILLA_VERSION"
+    log "ERROR: couldn't find a matching manifest entry for $VANILLA_VERSION"
     exit 1
   fi
   debug "Found version manifest at $versionManifestUrl"
 
-  serverDownloadUrl=$(get --json-path '$.downloads.server.url' "${versionManifestUrl}")
-  result=$?
-  if [ $result != 0 ]; then
-    log "ERROR failed to obtain version manifest from $versionManifestUrl ($result)"
+  if ! serverDownloadUrl=$(get --json-path '$.downloads.server.url' "${versionManifestUrl}"); then
+    log "ERROR: failed to obtain version manifest from $versionManifestUrl ($result)"
     exit 1
   elif [ "$serverDownloadUrl" = "null" ]; then
-    log "ERROR version $VANILLA_VERSION does not provide a server download"
+    log "ERROR: there is not a server download for version $VANILLA_VERSION"
     exit 1
   fi
 
@@ -36,7 +34,7 @@ if [ ! -e "$SERVER" ] || [ -n "$FORCE_REDOWNLOAD" ]; then
   get -o "$SERVER" "$serverDownloadUrl"
   result=$?
   if [ $result != 0 ]; then
-    log "ERROR failed to download server from $serverDownloadUrl ($result)"
+    log "ERROR: failed to download server from $serverDownloadUrl ($result)"
     exit 1
   fi
 fi
