When ICON is GIF, extract only first frame
Fixes #1303

diff --git a/scripts/start-finalExec b/scripts/start-finalExec
--- a/scripts/start-finalExec
+++ b/scripts/start-finalExec
@@ -5,13 +5,19 @@
 isDebugging && set -x
 
 if [ -n "$ICON" ]; then
-    if [ ! -e server-icon.png ] || [ "${OVERRIDE_ICON}" == "TRUE" ]; then
+    if [ ! -e server-icon.png ] || isTrue "${OVERRIDE_ICON}"; then
       log "Using server icon from $ICON..."
       # Not sure what it is yet...call it "img"
-      curl -sSL -o /tmp/icon.img $ICON
-      specs=$(identify /tmp/icon.img | awk '{print $2,$3}')
-      if [ "$specs" = "PNG 64x64" ]; then
+      if ! get -o /tmp/icon.img "$ICON"; then
+        log "ERROR: failed to download icon from $ICON"
+        exit 1
+      fi
+      read -r -a specs < <(identify /tmp/icon.img | awk 'NR == 1 { print $2, $3 }')
+      if [ "${specs[0]} ${specs[1]}" = "PNG 64x64" ]; then
         mv /tmp/icon.img /data/server-icon.png
+      elif [ "${specs[0]}" = GIF ]; then
+        log "Converting GIF image to 64x64 PNG..."
+        convert "/tmp/icon.img[0]" -resize 64x64! /data/server-icon.png
       else
         log "Converting image to 64x64 PNG..."
         convert /tmp/icon.img -resize 64x64! /data/server-icon.png
