New logger with color and specific types. Code cleanup  (#3108)

diff --git a/scripts/start-deployForge b/scripts/start-deployForge
--- a/scripts/start-deployForge
+++ b/scripts/start-deployForge
@@ -6,36 +6,29 @@
 # shellcheck source=start-utils
 . "${SCRIPTS:-$(dirname "$0")}/start-utils"
 isDebugging && set -x
+resultsFile=/data/.run-forge.env
+
+function mc-image-helper-forge() {
+  mc-image-helper install-forge \
+    --output-directory=/data \
+    --results-file="${resultsFile}" \
+    --minecraft-version="${VERSION}" \
+    --force-reinstall="${FORGE_FORCE_REINSTALL}" "$@"
+}
 
 if [[ ${FORGE_INSTALLER} ]]; then
-  if ! mc-image-helper install-forge \
-    --output-directory=/data \
-    --results-file=/data/.run-forge.env \
-    --minecraft-version="${VERSION}" \
-    --forge-installer="${FORGE_INSTALLER}" \
-    --force-reinstall="${FORGE_FORCE_REINSTALL}"; then
-      log "ERROR failed to install Forge given installer ${FORGE_INSTALLER}"
+  if ! mc-image-helper-forge --forge-installer="${FORGE_INSTALLER}" ; then
+      logError "Failed to installForge given installer ${FORGE_INSTALLER}"
       exit 1
   fi
-
 else
-  if ! mc-image-helper install-forge \
-    --output-directory=/data \
-    --results-file=/data/.run-forge.env \
-    --minecraft-version="${VERSION}" \
-    --forge-version="${FORGE_VERSION}" \
-    --force-reinstall="${FORGE_FORCE_REINSTALL}"; then
-      log "ERROR failed to install Forge"
+  if ! mc-image-helper-forge --forge-version="${FORGE_VERSION}"; then
+      logError "Failed to install Forge"
       exit 1
   fi
-
 fi
 
-
-# grab SERVER and export it
-set -a
-source /data/.run-forge.env
-set +a
+applyResultsFile ${resultsFile}
 
 export FAMILY=FORGE
 
diff --git a/scripts/start-deployQuilt b/scripts/start-deployQuilt
--- a/scripts/start-deployQuilt
+++ b/scripts/start-deployQuilt
@@ -12,10 +12,18 @@ set -eu
 
 isDebugging && set -x
 
+function mc-image-helper-quilt(){
+  mc-image-helper install-quilt \
+    --loader-version="$QUILT_LOADER_VERSION" \
+    --minecraft-version="$VERSION" \
+    --output-directory=/data \
+    --results-file="$resultsFile" "$@"
+}
+
 resultsFile=/data/.quilt.env
 
 if [[ $QUILT_LAUNCHER ]]; then
-  log "WARNING: use of QUILT_LAUNCHER is a deprecated feature."
+  logWarning "Use of QUILT_LAUNCHER is a deprecated feature."
   SERVER="$QUILT_LAUNCHER"
   export SERVER
   resolveVersion
@@ -24,38 +32,24 @@ if [[ $QUILT_LAUNCHER ]]; then
   exec "${SCRIPTS:-/}start-setupWorld" "$@"
 
 elif [[ $QUILT_LAUNCHER_URL ]]; then
-  log "ERROR: QUILT_LAUNCHER_URL is not longer supported. Pre-download and use QUILT_LAUNCHER."
+  logError "QUILT_LAUNCHER_URL is not longer supported. Pre-download and use QUILT_LAUNCHER."
   exit 2
 
 elif [[ $QUILT_INSTALLER_URL ]]; then
-  if ! mc-image-helper install-quilt \
-    --loader-version="$QUILT_LOADER_VERSION" \
-    --minecraft-version="$VERSION" \
-    --output-directory=/data \
-    --results-file="$resultsFile" \
-    --installer-url="$QUILT_INSTALLER_URL"; then
-    log "ERROR: failed to install Quilt given custom installer URL $QUILT_INSTALLER_URL"
+  if ! mc-image-helper-quilt --installer-url="$QUILT_INSTALLER_URL"; then
+    logError "Failed to installQuilt given custom installer URL $QUILT_INSTALLER_URL"
     exit 2
   fi
 
 else
-  if ! mc-image-helper install-quilt \
-    --loader-version="$QUILT_LOADER_VERSION" \
-    --minecraft-version="$VERSION" \
-    --output-directory=/data \
-    --results-file="$resultsFile" \
-    --installer-version="$QUILT_INSTALLER_VERSION"; then
-    log "ERROR: failed to install Quilt given installer version $QUILT_INSTALLER_VERSION"
+  if ! mc-image-helper-quilt --installer-version="$QUILT_INSTALLER_VERSION"; then
+    logError "Failed to installQuilt given installer version $QUILT_INSTALLER_VERSION"
     exit 2
   fi
 
 fi
 
-# grab SERVER, VERSION and export it
-set -a
-# shellcheck disable=SC1090
-source "${resultsFile}"
-set +a
+applyResultsFile ${resultsFile}
 
 export FAMILY=FABRIC
 exec "${SCRIPTS:-/}start-setupWorld" "$@"
diff --git a/scripts/start-deployVanilla b/scripts/start-deployVanilla
--- a/scripts/start-deployVanilla
+++ b/scripts/start-deployVanilla
@@ -13,20 +13,20 @@ if [ ! -e "$SERVER" ] || [ -n "$FORCE_REDOWNLOAD" ]; then
   versionManifestUrl=$(get 'https://launchermeta.mojang.com/mc/game/version_manifest.json' | jq --arg VERSION "$VERSION" --raw-output '[.versions[]|select(.id == $VERSION)][0].url')
   result=$?
   if [ $result != 0 ]; then
-    log "ERROR: failed to obtain version manifest URL ($result)"
+    logError "Failed to obtain version manifest URL ($result)"
     exit 1
   fi
   if [ "$versionManifestUrl" = "null" ]; then
-    log "ERROR: couldn't find a matching manifest entry for $VERSION"
+    logError "Couldn't find a matching manifest entry for $VERSION"
     exit 1
   fi
   debug "Found version manifest at $versionManifestUrl"
 
   if ! serverDownloadUrl=$(get --json-path '$.downloads.server.url' "${versionManifestUrl}"); then
-    log "ERROR: failed to obtain version manifest from $versionManifestUrl ($result)"
+    logError "Failed to obtain version manifest from $versionManifestUrl ($result)"
     exit 1
   elif [ "$serverDownloadUrl" = "null" ]; then
-    log "ERROR: there is not a server download for version $VERSION"
+    logError "There is not a server download for version $VERSION"
     exit 1
   fi
 
@@ -35,19 +35,20 @@ if [ ! -e "$SERVER" ] || [ -n "$FORCE_REDOWNLOAD" ]; then
   get -o "$SERVER" "$serverDownloadUrl"
   result=$?
   if [ $result != 0 ]; then
-    log "ERROR: failed to download server from $serverDownloadUrl ($result)"
+    logError "Failed to download server from $serverDownloadUrl ($result)"
     exit 1
   fi
 fi
+minecraftServerJarPath=/data/minecraft_server.jar
 
 if versionLessThan 1.6; then
-  if ! [[ -L /data/minecraft_server.jar && /data/minecraft_server.jar -ef "/data/$SERVER" ]]; then
-    rm -f /data/minecraft_server.jar
-    ln -s "/data/$SERVER" /data/minecraft_server.jar
+  if ! [[ -L $minecraftServerJarPath && $minecraftServerJarPath -ef "/data/$SERVER" ]]; then
+    rm -f $minecraftServerJarPath
+    ln -s "/data/$SERVER" $minecraftServerJarPath
   fi
   SERVER=minecraft_server.jar
-elif [[ -L /data/minecraft_server.jar ]]; then
-  rm -f /data/minecraft_server.jar
+elif [[ -L $minecraftServerJarPath ]]; then
+  rm -f $minecraftServerJarPath
 fi
 
 isDebugging && ls -l
diff --git a/scripts/start-finalExec b/scripts/start-finalExec
--- a/scripts/start-finalExec
+++ b/scripts/start-finalExec
@@ -7,37 +7,42 @@
 # shellcheck source=start-utils
 . "${SCRIPTS:-/}start-utils"
 isDebugging && set -x
+baseDataDir=/data
+tmpServerIconPath=/tmp/icon.img
+serverIconPath=${baseDataDir}/server-icon.png
+mcHealthEnvPath=${baseDataDir}/mc-health.env
+bootstrapPath=${baseDataDir}/bootstrap.txt
 
 if [ -n "$ICON" ]; then
     if [ ! -e server-icon.png ] || isTrue "${OVERRIDE_ICON}"; then
       log "Using server icon from $ICON..."
       if isURL "$ICON"; then
         # Not sure what it is yet...call it "img"
-        if ! get -o /tmp/icon.img "$ICON"; then
-          log "ERROR: failed to download icon from $ICON"
+        if ! get -o "$tmpServerIconPath" "$ICON"; then
+          logError "Failed to download icon from $ICON"
           exit 1
         fi
-        ICON=/tmp/icon.img
+        ICON="$tmpServerIconPath"
         iconSrc="url"
       elif [ -f "$ICON" ]; then
         iconSrc="file"
       else
-        log "ERROR: $ICON does not appear to be a URL or existing file"
+        logError "$ICON does not appear to be a URL or existing file"
         exit 1
       fi
       read -r -a specs < <(identify "$ICON" | awk 'NR == 1 { print $2, $3 }')
       if [ "${specs[0]} ${specs[1]}" = "PNG 64x64" ]; then
         if [ $iconSrc = url ]; then
-          mv -f /tmp/icon.img /data/server-icon.png
+          mv -f "$tmpServerIconPath" "$serverIconPath"
         else
-          cp -f "$ICON" /data/server-icon.png
+          cp -f "$ICON" "$serverIconPath"
         fi
       elif [ "${specs[0]}" = GIF ]; then
         log "Converting GIF image to 64x64 PNG..."
-        convert "$ICON"[0] -resize 64x64! /data/server-icon.png
+        convert "$ICON"[0] -resize 64x64! "$serverIconPath"
       else
         log "Converting image to 64x64 PNG..."
-        convert "$ICON" -resize 64x64! /data/server-icon.png
+        convert "$ICON" -resize 64x64! "$serverIconPath"
       fi
     fi
 fi
@@ -45,10 +50,9 @@ fi
 canUseRollingLogs=true
 useFallbackJvmFlag=false
 
+SERVER_DIR="$baseDataDir"
 if [[ ${FTB_DIR:-} ]]; then
   SERVER_DIR="$FTB_DIR"
-else
-  SERVER_DIR=/data
 fi
 
 
@@ -56,7 +60,7 @@ patchLog4jConfig() {
   file=${1?}
   url=${2?}
   if ! get -o "${SERVER_DIR}/${file}" "$url"; then
-    log "ERROR: failed to download corrected log4j config, fallback to JVM flag"
+    logError "Failed to download corrected log4j config, fallback to JVM flag"
     useFallbackJvmFlag=true
     return 1
   fi
@@ -101,7 +105,7 @@ fi
 
 if isTrue "${ENABLE_ROLLING_LOGS:-false}"; then
   if ! ${canUseRollingLogs}; then
-    log "ERROR: Using rolling logs is currently not possible in the selected version due to CVE-2021-44228"
+    logError "Using rolling logs is currently not possible in the selected version due to CVE-2021-44228"
     exit 1
   fi
   # Set up log configuration
@@ -214,31 +218,31 @@ if [[ ${INIT_MEMORY} || ${MAX_MEMORY} ]]; then
 fi
 
 function copyFilesForCurseForge() {
-  if [ ! -e "${FTB_DIR}/server-icon.png" ] && [ -e /data/server-icon.png ]; then
-    cp -f /data/server-icon.png "${FTB_DIR}/"
+  if [ ! -e "${FTB_DIR}/server-icon.png" ] && [ -e "$serverIconPath" ]; then
+    cp -f "$serverIconPath" "${FTB_DIR}/"
   fi
 
-  cp -f /data/eula.txt "${FTB_DIR}/"
+  cp -f ${baseDataDir}/eula.txt "${FTB_DIR}/"
 }
 
 if versionLessThan 'b1.8'; then
   echo "
 DISABLE_HEALTHCHECK=true
-  " > /data/.mc-health.env
+  " > "$mcHealthEnvPath"
 elif versionLessThan 1.7; then
   echo "
 MC_HEALTH_EXTRA_ARGS=(
   --use-server-list-ping
 )
-  " > /data/.mc-health.env
+  " > "$mcHealthEnvPath"
 elif isTrue "$USES_PROXY_PROTOCOL"; then
   echo "
 MC_HEALTH_EXTRA_ARGS=(
   --use-proxy
 )
-  " > /data/.mc-health.env
+  " > "$mcHealthEnvPath"
 else
-  rm -f /data/.mc-health.env
+  rm -f "$mcHealthEnvPath"
 fi
 
 mcServerRunnerArgs=(
@@ -257,7 +261,7 @@ fi
 if [[ ${TYPE} == "CURSEFORGE" && "${SERVER}" ]]; then
   copyFilesForCurseForge
 
-  cd "${FTB_DIR}" || (log "ERROR: can't go into ${FTB_DIR}"; exit 1)
+  cd "${FTB_DIR}" || (logError "Can't go into ${FTB_DIR}"; exit 1)
   log "Starting CurseForge server in ${FTB_DIR}..."
   if isTrue "${DEBUG_EXEC}"; then
     set -x
@@ -279,7 +283,7 @@ EOF
     sed -i "s/MAX_RAM=[^;]*/MAX_RAM=${MAX_MEMORY}/" "${FTB_DIR}/settings.cfg"
   fi
 
-  cd "${FTB_DIR}" || (log "ERROR: can't go into ${FTB_DIR}"; exit 1)
+  cd "${FTB_DIR}" || (logError "Can't go into ${FTB_DIR}"; exit 1)
   log "Running FTB ${FTB_SERVER_START} in ${FTB_DIR} ..."
 
   finalArgs="${FTB_SERVER_START}"
@@ -315,8 +319,8 @@ elif [[ $SERVER =~ run.sh ]]; then
   exec mc-server-runner "${mcServerRunnerArgs[@]}" --shell bash "${SERVER}" $EXTRA_ARGS
 else
   # If we have a bootstrap.txt file... feed that in to the server stdin
-  if [ -f /data/bootstrap.txt ]; then
-    bootstrapArgs="--bootstrap /data/bootstrap.txt"
+  if [ -f $bootstrapPath ]; then
+    bootstrapArgs="--bootstrap $bootstrapPath"
   fi
 
   log "Starting the Minecraft server..."
diff --git a/scripts/start-utils b/scripts/start-utils
--- a/scripts/start-utils
+++ b/scripts/start-utils
@@ -8,7 +8,7 @@ function get_from_gh() {
     fi
     if [[ ! "$oAuthScopes" =~ ^x-oauth-scopes:[[:space:]]*$ ]]; then
       # Don't use what you don't have to...
-      log "ERROR: GH_TOKEN has permissions it doesn't need. Recreate or update this personal access token and disable ALL scopes."
+      logError "GH_TOKEN has permissions it doesn't need. Recreate or update this personal access token and disable ALL scopes."
       exit 1
     else
       curl -fsSL -H "Authorization: token $GH_TOKEN" "${@:2}" "$1"
@@ -16,6 +16,14 @@ function get_from_gh() {
   else
     curl -fsSL "${@:2}" "$1"
   fi
+}
+
+function applyResultsFile() {
+  # grab SERVER and export it
+  set -a
+  # shellcheck disable=SC1090
+  source "$1"
+  set +a
 }
 
 function join_by() {
@@ -47,7 +55,7 @@ function isValidFileURL() {
 function resolveEffectiveUrl() {
   url="${1:?Missing required url argument}"
   if ! curl -Ls -o /dev/null -w "%{url_effective}" "$url"; then
-    log "ERROR failed to resolve effective URL from $url"
+    logError "Failed to resolve effective URL from $url"
     exit 2
   fi
 }
@@ -109,8 +117,105 @@ function log() {
   if isDebugging || isTrue "${LOG_TIMESTAMP:-false}"; then
     ts=" $(date --rfc-3339=seconds)"
   fi
-  echo "[init]${ts} $*"
+  echo -e "[init]${ts} $*"
   eval "$oldState"
+}
+
+function getSudoFromDistro(){
+  distro=$(getDistro)
+  command=
+  if [[ $distro == alpine ]]; then
+    command="su-exec"
+  else
+    command="gosu"
+  fi
+  echo $command
+}
+
+# Refer to https://unix.stackexchange.com/a/10065/102376
+function isTerminal() {
+  if test -t 1; then
+    # see if it supports colors...
+    ncolors=$(tput colors)
+    test -n "$ncolors" && test "$ncolors" -ge 8
+  else
+    return 1
+  fi
+}
+
+errorLogTag="[ERROR]"
+warningLogTag="[WARN]"
+
+if isTerminal; then
+  normal="$(tput sgr0)"
+  red="$(tput setaf 1)"
+  yellow="$(tput setaf 3)"
+  function getErrorColoredLogString() {
+    echo "${red}$errorLogTag $* ${normal}"
+  }
+  function getWarningColoredLogString() {
+    echo "${yellow}$warningLogTag $* ${normal}"
+  }
+else
+  function getErrorColoredLogString() {
+    echo "$errorLogTag $*"
+  }
+  function getWarningColoredLogString() {
+    echo "$warningLogTag $*"
+  }
+fi
+
+function error() {
+  echo -e "$(getErrorColoredLogString "$*")"
+}
+
+function logError() {
+  if isDebugging; then
+    set +x
+  fi
+  log "$(getErrorColoredLogString "$*")"
+  if isDebugging; then
+    set -x
+  fi
+}
+
+function warning() {
+  if isDebugging; then
+    set +x
+  fi
+  echo -e "$(getWarningColoredLogString "$*")"
+  if isDebugging; then
+    set -x
+  fi
+}
+
+function logWarning() {
+  log "$(getWarningColoredLogString "$*")"
+}
+
+function isNumeric() {
+  [[ $1 =~ ^[0-9]+$ ]]
+}
+
+function isNumericElseSetToDefault() {
+  local var_name="$1"
+  local default_value="$2"
+  
+  if ! isNumeric ${!var_name} ; then
+    eval "$var_name=$default_value"
+    export "$var_name"
+    logWarning "$var_name is not numeric, set to $default_value (seconds)"
+  fi
+}
+
+function checkIfNotZeroElseSetToDefault() {
+  local var_name="$1"
+  local default_value="$2"
+  if [ "${!var_name}" -eq "0" ] ; then
+    eval "$var_name=$default_value"
+    export "$var_name"
+    logWarning "$var_name must not be 0, set to $default_value (seconds)"
+  fi
 }
 
 function logAutopause() {
@@ -255,37 +360,12 @@ function versionLessThan() {
   compare_version "${VERSION}" "lt" "${1?}"
 }
 
-requireVar() {
-  if [ ! -v "$1" ]; then
-    log "ERROR: $1 is required to be set"
-    exit 1
-  fi
-  if [ -z "${!1}" ]; then
-    log "ERROR: $1 is required to be set"
-    exit 1
-  fi
-}
-
-requireEnum() {
-  var=${1?}
-  shift
-
-  for allowed in "$@"; do
-    if [[ ${!var} = "$allowed" ]]; then
-      return 0
-    fi
-  done
-
-  log "ERROR: $var must be set to one of $*"
-  #  exit 1
-}
-
 function writeEula() {
   if ! echo "# Generated via Docker
 # $(date)
 eula=${EULA,,}
 " >/data/eula.txt; then
-    log "ERROR: unable to write eula to /data. Please make sure attached directory is writable by uid=${UID}"
+    logError "Unable to write eula to /data. Please make sure attached directory is writable by uid=${UID}"
     exit 2
   fi
 }
@@ -354,7 +434,7 @@ function extract() {
     tar -C "${destDir}" --use-compress-program=unzstd -xf "${src}"
     ;;
   *)
-    log "ERROR: unsupported archive type: $type"
+    logError "Unsupported archive type: $type"
     return 1
     ;;
   esac
@@ -429,7 +509,7 @@ function ensureRemoveAllModsOff() {
   reason=${1?}
 
   if isTrue "${REMOVE_OLD_MODS:-false}"; then
-    log "WARNING using REMOVE_OLD_MODS interferes with $reason -- it is now disabled"
+    logWarning "Using REMOVE_OLD_MODS interferes with $reason -- it is now disabled"
     REMOVE_OLD_MODS=false
   fi
 }
