Use new helper github download-latest-asset command

diff --git a/scripts/start-deployKetting b/scripts/start-deployKetting
--- a/scripts/start-deployKetting
+++ b/scripts/start-deployKetting
@@ -4,38 +4,27 @@
 . "${SCRIPTS:-/}start-utils"
 isDebugging && set -x
 
-: "${KETTING_LAUNCHER_VERSION:=1.3.0}
-
-if [ ! -f kettinglauncher.jar ] && \
-  !( \
-    downloadUrl="https://github.com/kettingpowered/kettinglauncher/releases/download/v${KETTING_LAUNCHER_VERSION}/kettinglauncher-${KETTING_LAUNCHER_VERSION}.jar" || \
-    downloadUrl="https://nexus.c0d3m4513r.com/repository/Ketting/org/kettingpowered/kettinglauncher/${KETTING_LAUNCHER_VERSION}/kettinglauncher-${KETTING_LAUNCHER_VERSION}.jar" \
-  )
-then
-  log "ERROR failed to download Ketting Launcher Version ${KETTING_LAUNCHER_VERSION}?"
-  exit 1
+if ! SERVER=$(mc-image-helper github download-latest-asset \
+  --output-directory=/data \
+  --name-pattern="kettinglauncher-.+?(?<!-sources)\.jar" \
+  kettingpowered/kettinglauncher
+  ); then
+    log "ERROR: failed to download Ketting launcher"
+    exit 1
 fi
 
-if [[ $downloadUrl == null ]]; then
-  log "ERROR failed to download Ketting Launcher Version ${KETTING_LAUNCHER_VERSION}?"
-  log "ERROR KettingLauncher does not seem to be available for the Version ${KETTING_LAUNCHER_VERSION}"
-  exit 1
- fi
-
-if ! SERVER=$(get --output-filename --skip-up-to-date --output /data "$downloadUrl"); then
-  log "ERROR: failed to download Ketting server jar from $downloadUrl"
-  exit 1
-fi
+export SERVER
 
 resolveVersion
 
 EXTRA_ARGS+="-minecraftVersion $VERSION"
-if [[ $KETTING_VERSION != null ]]; then
+if [[ ${KETTING_VERSION:-} ]]; then
   EXTRA_ARGS+="-kettingVersion $KETTING_VERSION"
 fi
-if [[ $FORGEVERSION != null ]]; then
-  EXTRA_ARGS+="-forgeVersion $FORGEVERSION"
+if [[ ${FORGE_VERSION:-} ]]; then
+  EXTRA_ARGS+="-forgeVersion $FORGE_VERSION"
 fi
+export EXTRA_ARGS
 
 export SERVER
 export FAMILY=HYBRID
