fix : PR comments

diff --git a/scripts/start-deployCanyon b/scripts/start-deployCanyon
--- a/scripts/start-deployCanyon
+++ b/scripts/start-deployCanyon
@@ -13,7 +13,7 @@ if [ "${VERSION}" != "b1.7.3" ]; then
   exit 1
 fi
 
-canyonJob="https://canyonmodded.p0rtal.gay/job/Canyonmodded"
+canyonJob="https://jenkins.glass-launcher.net/job/Canyon"
 githubUrl="https://github.com/KoboDev/SupplyAndDemand/releases/download"
 canyonBuildJSON=$(curl -fsSL "${canyonJob}/${CANYON_BUILD}/api/json")
 
@@ -50,7 +50,7 @@ if [ ! -f "$SERVER" ]; then
     fi
     curl -fsSL -o "$SERVER" "$downloadUrl"
     if [ ! -f "$SERVER" ]; then
-      logErrorDownload "from $downloadUrl (status=$?)"
+      logError "Failed to download from $downloadUrl (status=$?)"
       exit 3
     fi
 fi
diff --git a/scripts/start-deployFabric b/scripts/start-deployFabric
--- a/scripts/start-deployFabric
+++ b/scripts/start-deployFabric
@@ -12,42 +12,39 @@ export TYPE=FABRIC
 
 resultsFile=/data/.install-fabric.env
 
-function mc-image-helper-fabric() {
-  mc-image-helper install-fabric-loader \
-    --results-file=${resultsFile} \
-    "$@"
-}
-
 isDebugging && set -x
 
 # Custom fabric jar
 if [[ $FABRIC_LAUNCHER ]]; then
-  if ! mc-image-helper-fabric \
+  if !   mc-image-helper install-fabric-loader \
+    --results-file=${resultsFile} \
     --from-local-file="$FABRIC_LAUNCHER"; then
-    logErrorFailedTo "use provided Fabric launcher"
+    logError "Failed to use provided Fabric launcher"
     exit 1
   fi
 
 # Custom fabric jar url
 elif [[ $FABRIC_LAUNCHER_URL ]]; then
-  if ! mc-image-helper-fabric \
+  if !   mc-image-helper install-fabric-loader \
+    --results-file=${resultsFile} \
     --from-url="$FABRIC_LAUNCHER_URL"; then
-    logErrorInstall "Fabric launcher from $FABRIC_LAUNCHER_URL"
+    logError "Failed to installFabric launcher from $FABRIC_LAUNCHER_URL"
     exit 1
   fi
 
 # Official fabric launcher
 else
-  if ! mc-image-helper-fabric \
+  if !   mc-image-helper install-fabric-loader \
+    --results-file=${resultsFile} \
     --minecraft-version="${VERSION}" \
     --installer-version="${FABRIC_LAUNCHER_VERSION}" \
     --loader-version="${FABRIC_LOADER_VERSION}"; then
-    logErrorInstall "Fabric launcher given $VERSION, $FABRIC_LAUNCHER_VERSION, $FABRIC_LOADER_VERSION"
+    logError "Failed to installFabric launcher given $VERSION, $FABRIC_LAUNCHER_VERSION, $FABRIC_LOADER_VERSION"
     exit 1
   fi
 fi
 
-grabServerAndExport
+applyResultsFile ${resultsFile}
 
 export FAMILY=FABRIC
 exec "${SCRIPTS:-/}start-setupWorld" "$@"
diff --git a/scripts/start-deployLimbo b/scripts/start-deployLimbo
--- a/scripts/start-deployLimbo
+++ b/scripts/start-deployLimbo
@@ -22,7 +22,7 @@ baseUrl="https://ci.loohpjames.com/job/Limbo/${LIMBO_BUILD}"
 buildInfoUrl="${baseUrl}/api/json"
 buildJson=$(curl -fsSL "${buildInfoUrl}")
 if [ $? != 0 ]; then
-  logErrorFailedTo "get build info from ${buildInfoUrl} (status=$?)"
+  logError "Failed to get build info from ${buildInfoUrl} (status=$?)"
   exit 1
 fi
 
@@ -45,7 +45,7 @@ if [ ! -f "$SERVER" ] || isTrue "$FORCE_REDOWNLOAD"; then
     downloadUrl="${baseUrl}/artifact/${artifactPath}"
     log "Downloading Limbo from $downloadUrl ..."
     if ! curl -fsSL -o "$SERVER" "$downloadUrl"; then
-      logErrorDownload "from $downloadUrl (status=$?)"
+      logError "Failed to download from $downloadUrl (status=$?)"
       exit 3
     fi
 
@@ -54,7 +54,7 @@ fi
 if [ ! -f "${LIMBO_SCHEMA_FILENAME}" ]; then
   log "Downloading default schem file"
   if ! curl -o "${LIMBO_SCHEMA_FILENAME}" -fsSL "${baseUrl}/artifact/${defaultSchemaPath}"; then
-      logErrorDownload "schema file $baseUrl (status=$?)"
+      logError "Failed to download schema file $baseUrl (status=$?)"
       exit 3
   fi
 fi
diff --git a/scripts/start-utils b/scripts/start-utils
--- a/scripts/start-utils
+++ b/scripts/start-utils
@@ -18,11 +18,11 @@ function get_from_gh() {
   fi
 }
 
-function grabServerAndExport() {
+function applyResultsFile() {
   # grab SERVER and export it
   set -a
   # shellcheck disable=SC1090
-  source "${resultsFile}"
+  source "$1"
   set +a
 }
 
@@ -55,7 +55,7 @@ function isValidFileURL() {
 function resolveEffectiveUrl() {
   url="${1:?Missing required url argument}"
   if ! curl -Ls -o /dev/null -w "%{url_effective}" "$url"; then
-    logErrorFailedTo "resolve effective URL from $url"
+    logError "Failed to resolve effective URL from $url"
     exit 2
   fi
 }
@@ -121,7 +121,7 @@ function log() {
   eval "$oldState"
 }
 
-function getCommandFromDistro(){
+function getSudoFromDistro(){
   distro=$(getDistro)
   command=
   if [[ $distro == alpine ]]; then
@@ -148,18 +148,6 @@ function logError() {
   log $(getErrorColoredLogString "$*")
 }
 
-function logErrorFailedTo() {
-  logError "Failed to $*"
-}
-
-function logErrorDownload() {
-  logErrorFailedTo "download $*"
-}
-
-function logErrorInstall() {
-  logErrorFailedTo "install $*"
-}
-
 function warning() {
   echo -e $(getWarningColoredLogString "$*")
 }
@@ -168,22 +156,18 @@ function logWarning() {
   log $(getWarningColoredLogString "$*")
 }
 
-function logAutoPauseAndStopChange() {
-   logWarning "$1, set to $2 (seconds)"
-}
-
-function checkIfNumeric() {
+function isNumeric() {
   [[ $1 =~ ^[0-9]+$ ]]
 }
 
-function checkIfNumericElseSetToDefault() {
+function isNumericElseSetToDefault() {
   local var_name="$1"
   local default_value="$2"
   
-  if ! checkIfNumeric ${!var_name} ; then
+  if ! isNumeric ${!var_name} ; then
     eval "$var_name=$default_value"
     export "$var_name"
-    logAutoPauseAndStopChange "$var_name is not numeric" $default_value
+    logWarning "$var_name is not numeric, set to $default_value (seconds)"
   fi
 }
 
@@ -193,7 +177,7 @@ function checkIfNotZeroElseSetToDefault() {
   if [ "${!var_name}" -eq "0" ] ; then
     eval "$var_name=$default_value"
     export "$var_name"
-    logAutoPauseAndStopChange "$var_name must not be 0" $default_value
+    logWarning "$var_name must not be 0, set to $default_value (seconds)"
   fi
 }
 
