Install Neoforge from a local file (#3918)
Co-authored-by: Geoff Bourne <itzgeoff@gmail.com>

diff --git a/scripts/start-deployNeoForge b/scripts/start-deployNeoForge
--- a/scripts/start-deployNeoForge
+++ b/scripts/start-deployNeoForge
@@ -2,6 +2,7 @@
 
 : "${NEOFORGE_VERSION:=latest}"
 : "${NEOFORGE_FORCE_REINSTALL:=false}}"
+: "${NEOFORGE_INSTALLER:=}"
 
 # shellcheck source=start-utils
 . "${SCRIPTS:-$(dirname "$0")}/start-utils"
@@ -9,14 +10,19 @@ isDebugging && set -x
 
 resultsFile=/data/.run-neoforge.env
 
-if ! mc-image-helper install-neoforge \
+if [[ ${NEOFORGE_INSTALLER} ]]; then
+  if ! mc-image-helper install-neoforge --neoforge-installer="${NEOFORGE_INSTALLER}" --output-directory=/data --results-file=${resultsFile} --minecraft-version="${VERSION}" --force-reinstall="${NEOFORGE_FORCE_REINSTALL}"; then
+    logError "Failed to installForge given installer ${NEOFORGE_INSTALLER}"
+    exit 1
+  fi
+elif ! mc-image-helper install-neoforge \
   --output-directory=/data \
   --results-file=${resultsFile} \
   --minecraft-version="${VERSION}" \
   --neoforge-version="${NEOFORGE_VERSION}" \
   --force-reinstall="${NEOFORGE_FORCE_REINSTALL}"; then
-    logError "Failed to install NeoForge"
-    exit 1
+  logError "Failed to install NeoForge"
+  exit 1
 fi
 
 applyResultsFile ${resultsFile}
