build: switch to matrix builds for Debian based variant builds (#1313)

diff --git a/scripts/start-configuration b/scripts/start-configuration
--- a/scripts/start-configuration
+++ b/scripts/start-configuration
@@ -66,9 +66,12 @@ if [[ $RCON_PASSWORD_FILE ]]; then
     log ""
 fi
 
+# Some Docker management UIs grab all the image declared variables and present them for configuration.
+# When upgrading images across Java versions, that creates a mismatch in PATH's expected by base image.
 if ! which java > /dev/null; then
-  log "Fixing PATH to include java"
-  PATH="${PATH}:/opt/java/openjdk/bin"
+  log "ERROR: PATH should not be explicitly passed into the container"
+  log "       Remove configuration of that variable."
+  exit 1
 fi
 
 export VERSIONS_JSON=https://launchermeta.mojang.com/mc/game/version_manifest.json
@@ -116,39 +119,30 @@ fi
 log "Resolving type given ${TYPE}"
 case "${TYPE^^}" in
   *BUKKIT|SPIGOT)
-    exec ${SCRIPTS:-/}start-deployBukkitSpigot "$@"
+    exec "${SCRIPTS:-/}start-deployBukkitSpigot" "$@"
   ;;
 
   PAPER)
-    exec ${SCRIPTS:-/}start-deployPaper "$@"
+    exec "${SCRIPTS:-/}start-deployPaper" "$@"
   ;;
 
   FORGE)
-    if versionLessThan 1.17; then
-    log "**********************************************************************"
-    log "WARNING: The image tag itzg/minecraft-server:java8 is recommended"
-    log "         since some mods require Java 8"
-    log "         Exception traces reporting ClassCastException: class jdk.internal.loader.ClassLoaders\$AppClassLoader"
-    log "         can be fixed with java8"
-    log "**********************************************************************"
-    fi
-    exec ${SCRIPTS:-/}start-deployForge "$@"
+    evaluateJavaCompatibilityForForge
+    exec "${SCRIPTS:-/}start-deployForge" "$@"
   ;;
 
   FABRIC)
-    exec ${SCRIPTS:-/}start-deployFabric "$@"
+    exec "${SCRIPTS:-/}start-deployFabric" "$@"
   ;;
 
   FTBA)
-    exec ${SCRIPTS:-/}start-deployFTBA "$@"
+    evaluateJavaCompatibilityForForge
+    exec "${SCRIPTS:-/}start-deployFTBA" "$@"
   ;;
 
   FTB|CURSEFORGE)
-    log "**********************************************************************"
-    log "NOTE: Some mods and modpacks may require Java 8."
-    log "      If so, use itzg/minecraft-server:java8"
-    log "**********************************************************************"
-    exec ${SCRIPTS:-/}start-deployCF "$@"
+    evaluateJavaCompatibilityForForge
+    exec "${SCRIPTS:-/}start-deployCF" "$@"
   ;;
 
   VANILLA)
@@ -156,43 +150,47 @@ case "${TYPE^^}" in
   ;;
 
   SPONGEVANILLA)
-    exec ${SCRIPTS:-/}start-deploySpongeVanilla "$@"
+    exec "${SCRIPTS:-/}start-deploySpongeVanilla" "$@"
   ;;
 
   CUSTOM)
-    exec ${SCRIPTS:-/}start-deployCustom "$@"
+    evaluateJavaCompatibilityForForge
+    exec "${SCRIPTS:-/}start-deployCustom" "$@"
   ;;
 
   MAGMA)
-    exec ${SCRIPTS:-/}start-deployMagma "$@"
+    evaluateJavaCompatibilityForForge
+    exec "${SCRIPTS:-/}start-deployMagma" "$@"
   ;;
 
   MOHIST)
-    exec ${SCRIPTS:-/}start-deployMohist "$@"
+    evaluateJavaCompatibilityForForge
+    exec "${SCRIPTS:-/}start-deployMohist" "$@"
   ;;
 
   CATSERVER)
-    exec ${SCRIPTS:-/}start-deployCatserver "$@"
+    evaluateJavaCompatibilityForForge
+    exec "${SCRIPTS:-/}start-deployCatserver" "$@"
   ;;
 
   PURPUR)
-    exec ${SCRIPTS:-/}start-deployPurpur "$@"
+    exec "${SCRIPTS:-/}start-deployPurpur" "$@"
   ;;
 
   AIRPLANE)
-    exec ${SCRIPTS:-/}start-deployAirplane "$@"
+    exec "${SCRIPTS:-/}start-deployAirplane" "$@"
   ;;
 
   PUFFERFISH)
-    exec ${SCRIPTS:-/}start-deployPufferfish "$@"
+    exec "${SCRIPTS:-/}start-deployPufferfish" "$@"
   ;;
 
   CANYON)
-    exec ${SCRIPTS:-/}start-deployCanyon "$@"
+    exec "${SCRIPTS:-/}start-deployCanyon" "$@"
   ;;
 
   LIMBO)
-    exec ${SCRIPTS:-/}start-deployLimbo "$@"
+    exec "${SCRIPTS:-/}start-deployLimbo" "$@"
   ;;
 
   CRUCIBLE)
diff --git a/scripts/start-deployForge b/scripts/start-deployForge
--- a/scripts/start-deployForge
+++ b/scripts/start-deployForge
@@ -38,18 +38,23 @@ install() {
     get_installer "$normForgeVersion" "$shortForgeVersion"
   fi
 
-  log "Installing Forge $shortForgeVersion using $FORGE_INSTALLER"
+  log "Installing Forge $shortForgeVersion. This might take a minute or two..."
   mkdir -p mods
   tries=3
-  while ((--tries >= 0)); do
-    if java -jar "$FORGE_INSTALLER" --installServer; then
-      break
+  while true; do
+    if ! java -jar "$FORGE_INSTALLER" --installServer &> forge-installer.log; then
+      if ((--tries <= 0)); then
+        cat forge-installer.log
+        log "
+ERROR Forge failed to install after several tries.
+"
+        exit 1
+      fi
+      log "Install failed. Trying again..."
+    else
+      break # out of this loop
     fi
   done
-  if ((tries < 0)); then
-    log "Forge failed to install after several tries." >&2
-    exit 10
-  fi
   # NOTE $shortForgeVersion will be empty if installer location was given to us
   log "Finding installed server jar..."
   unset -v latest
@@ -148,4 +153,5 @@ else
 fi
 
 export FAMILY=FORGE
+
 exec "${SCRIPTS:-/}start-setupWorld" "$@"
