Removed catserver and updated magma download (#3751)
Co-authored-by: Geoff Bourne <itzgeoff@gmail.com>

diff --git a/scripts/start-deployMagma b/scripts/start-deployMagma
--- a/scripts/start-deployMagma
+++ b/scripts/start-deployMagma
@@ -8,18 +8,14 @@ isDebugging && set -x
 
 resolveVersion
 
-if ! downloadUrl=$(get --json-path '$.link' "https://api.magmafoundation.org/api/v2/${VERSION}/latest/${MAGMA_VERSION}"); then
-  logError "Failed to locate latest Magma download for ${VERSION}. Is that version supported?"
-  exit 1
+# Neo Magma currently supports just 1.21.x
+if [[ ! $VERSION = 1.21.* ]]; then
+logError "Magma does not support $VERSION (expected 1.21.x)"
+exit 1
 fi
 
-if [[ $downloadUrl == null ]]; then
-  logError "Magma does not seem to be available for $VERSION"
-  exit 1
-fi
-
-if ! SERVER=$(get --output-filename --skip-up-to-date --output /data "$downloadUrl"); then
-  logError "Failed to download Magma server jar from $downloadUrl"
+if ! SERVER=$(get --output-filename --skip-up-to-date --output /data "https://magmafoundation.org/api/versions/${MAGMA_VERSION}/download"); then
+  logError "Failed to download Magma server jar for $MAGMA_VERSION"
   exit 1
 fi
 
